/* ========================================================================= *\
 * DO NOT EDIT! This header file is generated by the script get_tz_values!   *
 * ------------------------------------------------------------------------- *
 *                ---  This file is in the public domain.  ---               *
\* ========================================================================= */

#ifndef _TZ_VALUE_H
#define _TZ_VALUE_H

#include <stddef.h> /* for size_t */

#ifdef __cplusplus
extern "C" {
#endif

typedef struct _TZ_VALUE TZ_VALUE;
struct  _TZ_VALUE
{
   const char * name; /* name of the location or time zone */
   const char * tz;   /* TZ value for the location or time zone */
};

extern struct TZ_VALUE timezones[]; /* NULL terminated array of TZ values */
size_t  num_timezones();            /* returns the array size of timezones */

#ifdef __cplusplus
}/* extern "C" */
#endif

#endif /* _TZ_VALUE_H */

/* ========================================================================= *\
 * END OF FILE                                                               *
\* ========================================================================= */
