/* ========================================================================= *\
 * DO NOT EDIT! This header file is generated by the script get_tz_values!   *
 * ------------------------------------------------------------------------- *
 *                ---  This file is in the public domain.  ---               *
\* ========================================================================= */

#ifndef _TZ_VALUE_H
#define _TZ_VALUE_H

#include <stddef.h> /* for size_t */

#ifdef __cplusplus
extern "C" {
#endif

typedef struct TZ_VALUE_S TZ_VALUE;
struct  TZ_VALUE_S
{
   const char * name; /* name of the location or time zone */
   const char * tz;   /* TZ value for the location or time zone */
};

extern TZ_VALUE timezones[]; /* NULL terminated array of TZ values */
extern size_t num_timezones;        /* numbers of timezones in the array */

#ifdef __cplusplus
}/* extern "C" */
#endif

#endif /* _TZ_VALUE_H */

/* ========================================================================= *\
 * END OF FILE                                                               *
\* ========================================================================= */
