/* ========================================================================= *\
 * DO NOT EDIT! This header file is generated by the script get_tz_values!   *
 * ------------------------------------------------------------------------- *
 *                ---  This file is in the public domain.  ---               *
\* ========================================================================= */

#ifndef _TZ_VALUE_H
#define _TZ_VALUE_H

#include <stddef.h> /* for size_t */

#ifdef __cplusplus
extern "C" {
#endif

typedef struct TZ_VALUE_S TZ_VALUE;
struct  TZ_VALUE_S
{
   const char * name; /* name of the location or time zone */
   const char * tz;   /* TZ value for the location or time zone */
};

extern TZ_VALUE timezones[]; /* NULL terminated array of TZ values */
extern size_t num_timezones; /* numbers of timezones in the array */

/* ------------------------------------------------------------------------- *\
   pc_find_TZ searches a location or a time zone name in the timezone array
   and returns either a pointer to the related TZ value or NULL if the name
   was not found in that array.
\* ------------------------------------------------------------------------- */
const char * pc_find_TZ(const char * name); 

#ifdef __cplusplus
}/* extern "C" */
#endif

#endif /* _TZ_VALUE_H */

/* ========================================================================= *\
 * END OF FILE                                                               *
\* ========================================================================= */
